### ISSUE TITLE
Build fails due to Checkstyle violations

### ISSUE THREAD

**Issue by polo-language** [prestodb/presto-jdbc-java6#15]
Build fails due to Checkstyle violations:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (default) on project presto-jdbc-java6: You have 10510 Checkstyle violations. -> [Help 1]

Compiling with Oracle SE JDK 1.6.0_45
Maven version 3.3.9

Was, however, able to compile by making the following changes in the pom.xml:
        <air.check.fail-checkstyle>false</air.check.fail-checkstyle>
        <air.check.skip-checkstyle>true</air.check.skip-checkstyle>

**Comment by maciejgrzybek** [comment]
Can you provide more details? A bit above the message you pasted maven provides an actual reason of checkstyle violation.
Did you change anything in source code?

**Comment by polo-language** [comment]
Building this on Windows, which seems to be the problem. The errors are all the same, looks like one for each line of source:
[ERROR] src\main\java\com\facebook\presto\jdbc\QueryExecutor.java[1](regexp) RegexpMultiline: Line contains carriage return

Didn't change the source manually at all, but using git "Checkout Windows-style".

**Comment by maciejgrzybek** [comment]
That's definitely an issue. We even have a Github issue for problems with building on Windows. The ticket is there: https://github.com/prestodb/presto/issues/2342. It's been there for a while though.
The easiest way so far is to install a VM with Ubuntu 14.04 and setup dev env in it.

**Comment by leolorenzoluis** [comment]
Any updates on this?

**Comment by blackhawkbigpunch** [comment]
Setting configuration of git core.autocrlf to false while cloning this repository bypassed the fail with maven-checkstyle-plugin issue in windows.

**Comment by findepi** [comment]
Yeah, you need to check out the sources as-is, without `core.autocrlf` "magic".

**Comment by dsjoegeo** [comment]
5.2K Jun 30 22:16 presto-db2-300.jar

**Comment by dsjoegeo** [comment]
I s that the final size of the jar

**Comment by dsjoegeo** [comment]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-db2 ---
[INFO] There are 4 errors reported by Checkstyle 8.7 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src/main/java/io/prestosql/plugin/db2/DB2Client.java:[21] (imports) ImportOrder: Wrong order for 'com.ibm.db2.jcc.DB2Driver' import.
[ERROR] src/main/java/io/prestosql/plugin/db2/DB2ClientModule.java:[18] (imports) ImportOrder: Wrong order for 'com.google.inject.Binder' import.
[ERROR] src/test/java/io/prestosql/plugin/db2/TestDB2Plugin.java:[19] (imports) ImportOrder: Wrong order for 'com.google.common.collect.ImmutableMap' import.
[ERROR] src/test/java/io/prestosql/plugin/db2/TestDB2Plugin.java:[21] (imports) ImportOrder: Extra separation in import group before 'org.testng.annotations.Test'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.870 s
[INFO] Finished at: 2019-06-30T22:20:20+00:00
